# Generated by Django 5.0.4 on 2024-04-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_food_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_item",
                to="api.food",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item",
                to="api.order",
            ),
        ),
    ]
